### ISSUE TITLE
How to use the Codemeta generator?

### ISSUE THREAD

**Issue by AugustinErnoult** [codemeta/codemeta-generator#33]
I'm sorry, I don't understand how to use the CodeMeta generator on webbrowser.
I completed almost all fields, but the only activate button is "reset form".

I tried also to copy-past in the codemeta.json box the file content from here: https://github.com/ropensci/codemetar/blob/main/codemeta.json
to try the "validate function" but the button is not activated...

I tried 2 browser (Firefox and chrome) without success. Do I miss something?

**Comment by ewan-escience** [comment]
I have the same, I think it's broken.

**Comment by ewan-escience** [comment]
It seems to come from an HTTP request to https://codemeta.github.io/data/contexts/codemeta-2.0.jsonld, which doesn't exist.

I think the bug was introduced in #27 in file js/codemeta_generation.js on line 14.

The URL https://codemeta.github.io/codemeta-generator/data/contexts/codemeta-2.0.jsonld does exist, which is what I think was intended.
